# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "amy"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pere Urbon-Bayes"]
  s.date = "2012-04-26"
  s.description = "Our REST API stenographer"
  s.email = "pere.urbon@gmail.com"
  s.executables = ["amy"]
  s.files = [
    "lib/amy.rb",
    "lib/amy/generate.rb",
    "lib/amy/models/main.rb",
    "lib/amy/models/resource.rb",
    "lib/amy/parser.rb",
    "views/js/amy.js",
    "views/main.erb.html",
    "views/resource.erb.html",
    "views/style/style.css"
  ]
  s.homepage = "http://github.com/purbon/amy"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Amy is the REST api stenographer"

  s.add_dependency('json')
  s.add_dependency('maruku')

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

